# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170727_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_reset',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u91cd\u8bbe\u5bc6\u7801'),
        ),
    ]
