# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-28 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_emailverifyrecord_is_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifyrecord',
            name='is_reset',
        ),
    ]
